### ISSUE TITLE
Imageserver: support vms ?

### ISSUE THREAD

**Issue by rmaree** [cytomine/Cytomine-core-legacy#1001]
Support vms ne marche plus (ou fichiers mal placés?):
http://beta.cytomine.be/#tabs-images-75609
Embêtant pour démos car projet le mieux annoté...

**Comment by stevben** [comment]
Me semble que c’est accessible pour toi de pouvoir vérifier. Qu’en est-il ?

**Comment by rmaree** [comment]
Il me semble que tu m'as dit l'autre jour que p-ê la raison pourrait
être que les fichiers étaient mal placés (ou avaient été déplacés ???),
mais je ne sais pas ce que tu sous-entendais par là et de mon côté je
n'ai rien changé à ces projets/images depuis des mois.

Il y a bien des fichiers sur l'image server dans:
./18/Neo22J_19-GAV-Gemzar-5 - 2011-12-26 12.51.50_clip.vms

Raphaël.

Le Sun, 02 Feb 2014 02:08:25 -0800
Benjamin Stévens notifications@github.com a écrit:

> Me semble que c’est accessible pour toi de pouvoir vérifier. Qu’en est-il ?
> 
> Le 2 févr. 2014 à 10:18, rmaree notifications@github.com a écrit :
> 
> > Support vms ne marche plus (ou fichiers mal placés?):
> > http://beta.cytomine.be/#tabs-images-75609
> > Embêtant pour démos car projet le mieux annoté...
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/cytomine/Cytomine_Core/issues/1001#issuecomment-33896706

## 

Raphaël Marée (PhD, GIGA Bioinformatics)
Raphael.Maree@ulg.ac.be  |  bioinformatics.giga@ulg.ac.be
http://www.montefiore.ulg.ac.be/~maree/ | http://www.giga.ulg.ac.be/
Tél.: +32 4 366 26 44 | Fax: +32 4 366 29 84

**Comment by stevben** [comment]
Fixed.

Openslide n'accepte pas les VMS sans l'attribut NoLayers.
J'ai recompilé OpenSlide dernière version sans cette vérification
