### ISSUE TITLE
Listing image very slow (search)

### ISSUE THREAD

**Issue by loic911** [cytomine/Cytomine-core-legacy#1007]
http://beta.cytomine.be/#tabs-images-57
=> 1 request needed (2,53 sec)

In search input, type "NEO"
=> 3 requests needed (4,31 ; 4,38 ; 4,29 sec)

In search input, type "NEO_4_CURCU"
=> 11 requests (8,47 ; 9,10 ; 10,12 .... sec)

**Comment by stevben** [comment]
Je teste et ça ne prend pas ce temps là chez moi

**Comment by loic911** [comment]
Les stats sur la version déployée shareview:
Temps moyen d'exécution de la méthode "be.cytomine.utils.DataTablesService.process" (566 accès) => 7,031 secondes de moyenne.

Pour les appels HTTP:
/api/project/8272189/imageinstance.json ajax GET     (79 appels) => moyenne 27,689 secondes
/api/project/8618416/imageinstance.json ajax GET     (46 appels) => moyenne de 19,675 secondes
/api/project/8738470/imageinstance.json ajax GET     (5 appels) => moyenne de 10,784 secondes  
...

Ces stats ont surement été collectée avec plusieurs utilisateurs dessus en même temps (contrairement a beta).

**Comment by loic911** [comment]
Bonjour, 
Lorsque je suis dans un projet (n'importe lequel), les différentes images ne s'affichent pas. "processing..." s'affiche sans arrêt. C'était déjà le cas hier 
Merci pour votre aide, 
V.Defaweux

Received on February 13, 2

Lié a ça?
