### ISSUE TITLE
Weird zoom buttons under firefox (Ubuntu)

### ISSUE THREAD

**Issue by 0asa** [cytomine/Cytomine-core-legacy#1009]
Am I the only one seing this : http://d.pr/i/oSe6 ?

**Comment by stevben** [comment]
Firefox bug only

Tu peux inspecter le DOM et dire ce que tu vois au niveau CSS, en particulier background-url ?

**Comment by 0asa** [comment]
C'est cette image qui est utilisée : /lib/OpenLayers-2.13.1/theme/default/img/zoom-panel.png
Mais je pense que ça vient du gradient, il n'est pas pris en charge tel quel par FF et donc fallback sur l'image. Donc, soit on change l'image soit on ajoute le gradient compatible FF.

**Comment by 0asa** [comment]
Faudra envisager d'ajouter les autres prefixes pour les gradients ou d'ajouter une seule couleur pour le fallback (et éviter de tomber sur l'image toute moche).
