### ISSUE TITLE
Remplacer OpenLayers 2

### ISSUE THREAD

**Issue by stevben** [cytomine/Cytomine-core-legacy#1019]
OL2 est maintenant fixé, la communauté est maintenant sur deux autres projets: 
- OpenLayers 3 (http://ol3js.org/)
- Leaflet JS (http://leafletjs.com/)

**Comment by geektortoise** [comment]
The concerned front-end is not supported anymore.

The new front-end use OpenLayers 5 via VueLayers 0.11.
