### ISSUE TITLE
Remplacer Farbastic

### ISSUE THREAD

**Issue by stevben** [cytomine/Cytomine-core-legacy#1027]
La licence OpenSource est problématique car imposerait de tout mettre en GPL

Remplacer par : http://lauren.github.io/pick-a-color/

**Comment by loic911** [comment]
Pas été remplacé partout (merge channel).

Je désactive l'appel aux anciennes méthodes pour l'instant.

**Comment by stevben** [comment]
Ah ok. J’avais fait un FIND & REPLACE pourtant.
Le remplacer prend quelques secondes, une classe sur le champ et l’appel sur l’element JQuery.

**Comment by loic911** [comment]
J'ai pour l'instant juste remplacer le js en "urgence".

Je ne déploierais pas auj donc le fix peut attendre.

**Comment by geektortoise** [comment]
MIT licence
