### ISSUE TITLE
Upload refactoring

### ISSUE THREAD

**Issue by loic911** [cytomine/Cytomine-core-legacy#1029]
La partie UPLOAD d'IMS devient difficilement maintenable.
Il y a plusieurs raisons:
-le code a migré de Cytomine vers IMS sans bouger,
-le support nginx upload,
-le support/fix nouvelles images a été ajouté au fur et a mesure,
-peu ou pas de doc/commentaire,
-...

Il faudrait repartir de 0 sur base du nouveau workflow (nginx upload => ims => cytomine) et sur base d'un dataset d'image représentatif avec des tests automatisés et une bonne doc.

**Comment by stevben** [comment]
Yo,

J'ai déjà les images avec lesquelles je teste.
Ca prend quelques GIGAS, il faudrait un moyen de les partager facilement.

**Comment by stevben** [comment]
Je ferme ce ticket. De nouveaux tickets devront être créés dans IMS pour découper le travail à effectuer
