### ISSUE TITLE
Récupérer clé publique et privée d'un user

### ISSUE THREAD

**Issue by rmaree** [cytomine/Cytomine-core-legacy#1033]
En tant qu'admin, offrir possibilité de récupérer clé publique et privée d'un user à partir de son id.

Pour le moment le service /userkey/{publicKey}/keys.json  demande la clé publique du user.

**Comment by stevben** [comment]
Pour quel usage ?

**Comment by rmaree** [comment]
Quand un utilisateur a une demande particulière ou suite à une erreur que je corrige alors par script (ex: il a fait 20 000 annotations mais sans leur associer de terme).

Je comprends que c'est touchy. Ne devrait être accessible que pour les admins, est-ce justifié d'en faire un service ou autre moyen ?

**Comment by stevben** [comment]
Ok mais si tu es admin, tu peux le faire à ton nom. C'est embêtant ?

**Comment by loic911** [comment]
Si Raphaël le fait a son nom, les termes apparaîtront différemment à l'utilisateur.

Il y a déjà un service pour lister les clés, mais sur base de clé public. Impossible de connaitre la clé public de qqun d'autre via service. Il faut un service pour connaitre la clé public d'un utilisateur.

**Comment by stevben** [comment]
Bien entendu ça apparaîtra au nom de Raphaël mais dans les faits on obtient la même base de données pour l'apprentissage et les prédictions, ce qui est le but. 

On peut faire ce service mais je m'interroge sur sa nécessité et l'intérêt de se faire passer pour quelqu'un d'autre...

**Comment by loic911** [comment]
Je comprend. Dans ce cas-ci, c'est un problème lié à un oubli de l'utilisateur, ça ne me gène pas que le script soit lancé en son nom à sa demande. 
Ce qui par contre moi me gène, c'est qu'on réalise autant d'action en ADMIN en bypassant tout les contrôles et en mettant a mal la cohérence des données... Idéalement, le gros des actions devrait être effectuées en USER.

**Comment by rmaree** [comment]
Un exemple de cas concret: utilisateur X me demande de compter le nombre de "noyaux" dans sa lame, mais il me dit qu'il n'a pas assigné le terme "noyaux" à toutes ses annotations car soit ça buggait, soit il a oublié, soit blablabla, donc plein de points sans terme. En pratique: 15000 points dans sa lame. Soit je copie toutes les annotations dans ma couche ou je leur assigne le terme noyaux mais dans les deux cas c'est du gaspillage (je n'ai pas besoin d'avoir des données dans ce projet); soit j'assigne le terme directement en tant que X.
En pratique: je le fais déjà de me connecter en tant que X en demandant à l'utilisateur de me copier-coller ses clés publiques/privées, ce serait juste + facile de pouvoir les récupérer moi-même.

**Comment by stevben** [comment]
Je comprends bien le soucis également et tout faire en admin n'est pas la solution j'en conviens.

Pour cet exemple précis, tu n'as pas besoin de copier les annotations pour assigner un terme, mais il y a sans doute d'autres cas où ça ne marche pas. 

Le truc qui me dérange le plus, c'est que l'ADMIN a tous les droits, y compris de faire des actions au nom de quelqu'un d'autre en lui prenant ses clés. Si ce service doit exister, il doit selon moi être fait avec le consentement de l'utilisateur (c'est le cas quand il copie-colle) et les clés devraient expirer (voir être d'autres clés temporaires). 

Je ne dis pas qu'il faut implémenter tout ce processus (on peut juste faire le service pour l'instant), et faire des issues pour le reste.

**Comment by loic911** [comment]
Réglé lors du prochain déploiement:
-se mettre en session admin,
-aller dans le module admin,
-trouver le bon utilistaeur,
-cliquer sur "connect as this user"
-Les clés sont dispos dans la zone "account" ou via un  /api/user/current.json
