### ISSUE TITLE
Style review cyto

### ISSUE THREAD

**Issue by rmaree** [cytomine/Cytomine-core-legacy#1034]
Style review cyto à nettoyer car peu utilisable tel quel:

1) 4 thumbnails sur première ligne puis saut à la ligne 5ième thumbnail

2) box des termes rectangulaires prennent toute la ligne au lieu de carrés (plusieurs carrés par ligne comme avant)

3) boutons next pas lisibles

ex: http://beta.cytomine.be/#tabs-reviewdash-18013068
![review-cyto](https://cloud.githubusercontent.com/assets/3587894/2632285/fd047820-be62-11e3-8a0c-8c9545c5b5a4.png)
![review-cyto2](https://cloud.githubusercontent.com/assets/3587894/2632287/fe3e7b5a-be62-11e3-976e-3a4bc0dfdd29.png)

**Comment by rmaree** [comment]
- Add :hover when drag&drop into term boxes ?
- No data to display (right panel) ?

**Comment by loic911** [comment]
Ok for d&d and zindex.

But cannot reproduce "No data to display (right panel) ?"
