### ISSUE TITLE
IE8 Support

### ISSUE THREAD

**Issue by stevben** [cytomine/Cytomine-core-legacy#1038]
A lot of end-users will probably be on IE8 and we need to handle it.

**Comment by loic911** [comment]
You asked for it, you got it: jQuery 2.0 has arrived!

As promised, this version leaves behind the older Internet Explorer 6, 7, and 8 browsers. In return it is smaller, faster, and can be used in JavaScript environments where the code needed for old-IE compatibility often causes problems of its own.

=> On va s'amuser...

**Comment by stevben** [comment]
On peut toujours utiliser JQuery 1.9 non ?
Le problème c'est la méthode $().on() qui est pas mal utilisée.
On pourrait le faire en fonction du navigateur pour ne pas avoir du code préhistorique sur des browsers modernes

**Comment by stevben** [comment]
``` html
<!--[if (!IE)|(gt IE 8)]><!-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
<!--<![endif]-->

<!--[if lte IE 8]>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<![endif]-->
```

**Comment by loic911** [comment]
Oui c'est ce que j'avais trouvé.
Mais ce sera pas compatible avec IE10 (supprimé):

[if IE]
This content is ignored in IE10 and other browsers.
In older versions of IE it renders as part of the page.
[endif]

**Comment by stevben** [comment]
Pourquoi pas IE10 ?

**Comment by loic911** [comment]
voir au dessus, le message a été tronqué

**Comment by stevben** [comment]
Tu dois mettre des ``` quand y a du code comme ça ;-) Vu que c'est un comment HTML..

**Comment by stevben** [comment]
Tu sors ce bout de texte d'où ? Je ne comprends pas.

**Comment by loic911** [comment]
http://blogs.msdn.com/b/ie/archive/2011/07/06/html5-parsing-in-ie10.aspx

De ce que je comprend, il ne tiens pas compte des IF IE si la version est 10.

**Comment by loic911** [comment]
On progresse \o/

![selection_077](https://cloud.githubusercontent.com/assets/1715849/2913269/d67ba07c-d689-11e3-9308-78d2516ef92e.png)

**Comment by stevben** [comment]
Ok je comprends...
Il doit y avoir des solutions j'en suis sûr. Des gens en parlent ici : 
http://stackoverflow.com/questions/9900311/how-do-i-target-only-internet-explorer-10-for-certain-situations-like-internet-e

```
<script>if(Function('/*@cc_on return 10===document.documentMode@*/')()){document.documentElement.className='ie10';}</script>
```

**Comment by loic911** [comment]
Pour l'instant j'utilise du code gsp grails pour détecter ça.
Je verrais une fois que ça tourne (ou pas) sous ie8 comment emballer ça dans le viewport de manière propre.

T'avais testé sous ie9?

**Comment by stevben** [comment]
Non pas dernièrement, juste IE8

**Comment by stevben** [comment]
Des progrès ?

**Comment by loic911** [comment]
Oui j'ai un peu mis ça de coté pour l'instant.

J'étais arrivé au client qui se lance et les fonctions basiques (dashboard, affichage projet, ontologies,...) sont OK. J'ai pas encore tout passé en revue...

Il y a beaucoup d'incompatibilité (erreur js, erreur si html mal formé alors que ok avec chrome,...) donc il faudrait idéalement tout repasser en détail. C'est également beaucoup plus lent.
Le gros point d'incompatibilité est le non support de la librairie nvd3 (soit on désactive les charts, soit on trouve une autre solution).

**Comment by stevben** [comment]
Ok. Pour NVD3, on peut mettre un message indiquant que le navigateur est trop vieux (5 ans :D)

**Comment by loic911** [comment]
J'ai commencé a documenter ici:
http://confluence.cytomine.be/display/DEV/%5BNote%5D+Browser+support

Le base de l'applic fonctionne (projets, viewer,...) mais certaines parties ne fonctionnent pas (jobs, review,...). Ca prend énormément de temps et IE8 est assez pourris pour le debug.
Je pense qu'il est préférable de ne garder le support a IE8 qu'a ce qui est vraiment nécessaire.

Je ferme le ticket pour l'instant.
