### ISSUE TITLE
Display classification confusion matrix errors not correct

### ISSUE THREAD

**Issue by rmaree** [cytomine/Cytomine-core-legacy#1045]
When looking at a confusion matrix e.g. 
http://beta.cytomine.be/#tabs-algos-94152784-674179-130433846

When we want to display subsets of objects according to their classification, there is something wrong: the number of displayed objects does not correspond to the number indicated in the confusion matrix box.

e.g. clicking on the 12 (positive underdetermined x positive underdetermined) shows 16 objects instead of 12 objects.

**Comment by loic911** [comment]
Confusion matrix = 12
Server response = 36
Client listing = 16

I fix "Server response = 36" => Server response = 12. 
Client listing should be fix too.
