### ISSUE TITLE
Outil screenshot avec scalebar

### ISSUE THREAD

**Issue by stevben** [cytomine/Cytomine-core-legacy#1050]
L'absence de scale bar rend l'outil anodin selon certains utilisateurs. Il faudrait pouvoir en incruster une librarie graphique équivalente à GD pour Java

**Comment by stevben** [comment]
Une autre option est de faire un rendu PNG du DOM dans webkit (peut-être serveur SIDE).

http://www.paulhammond.org/webkit2png/

**Comment by stevben** [comment]
Pour info, possible de le faire en JS aussi 

http://html2canvas.hertzen.com/

**Comment by loic911** [comment]
webkit2png ne fonctionne que sur mac.
"Sorry, but webkit2png relies on PyObjC, the python/Objective C bridge, to connect with Mac OS X's Cocoa API. Since the Cocoa framework isn't available on non-Mac platforms, porting webkit2png isn't possible"

J'ai testé une lib java html2image. Je pensais envoyé le DOM de la scalebar, générer un png et le coller sur l'image. Malheusrement il ne respecte pas les tailles (image = +-125-150% de la scalebar). Si je la réduit (au pifomètre), ca devient illisible.

Je pense faire plus simple: récupérer la longueur de la scalebar (via jquery) + les textes avec les mesures et dessiner ça avec awt ou autre.

**Comment by stevben** [comment]
OK AWT, c'était le premier scénario envisagé et probablement le plus simple, solide et sans nouvelles dépendances.

**Comment by loic911** [comment]
Pour l'instant le traitement est fait coté Core. Il suffira de copier le code dans l'IMS (j'ai pas réussi a mettre en place localement le nouveau workflow avec l'IMS)

**Comment by loic911** [comment]
ok c'est déplacé vers IMS

**Comment by loic911** [comment]
Ca fonctionne pour des niveau de zoom élevé mais si on dézoom la scale bar n'est pas correcte.
Si on demande une image w*h, on peut recevoir, selon le zoom, des images plus petites. 

Le problème c'est que la proportion n'est pas toujours gardée (il semblerait qu'on coupe des parties de l'image).

//largeur demandée
params.int('width')=22400

//largeur obtenue
real('width')=4597

//largeur demandée/hauteur demandée
proport1=1.9801980198019802

//largeur obtenue/hauteur obtenue
proport2=1.6255304101838755

L'image a été tronquée en largeur, ce qui faussera tout calcul (l'image de 4597 ne couvre pas la même distance sur la lame que celle de 22400).
On peut obtenir une valeur de largeur correct si on est sur que l'image n'a pas été tronquée en hauteur aussi (sinon aucune garantie que le calcul sera correct)

Pour l'instant une exception est simplement lancée si proport1<>proport2

**Comment by stevben** [comment]
OpenLayers renvoie les "bounds" de l'image visible au niveau maximum (donc sans tenir compte de l'interface utilisateur). Tu peux fournir le params 'zoom' au service crop pour avoir la bonne taille en retour (au niveau de zoom de l'utilisateur). Le service renvoie une image avec width_lvl_0 / 2^zoom & height_lvl_0 / 2^zoom ce qui devrait correspondre à ce que tu attends. Par défault, zoom = 0.

**Comment by loic911** [comment]
Le problème c'est que le service "camera" reçoit un crop d'IIP sur un niveau de zoom variable et qu'il n'est pas possible de le spécifier. 
Je suppose qu'IIP tente de renvoyer l'image au niveau de zoom max, si elle est trop grande, il tente un niveau de zoom inférieur. 

Parfois il supprime une partie de la largeur de l'image (je suppose en dehors de la vrai image). Si l'image n'était pas tronquée, on pourrait retrouver la différence de width entre l'image demandée et l'image reçue. Si elle est tronquée, il n'est plus possible de faire le lien en x% de la largeur en px = n mm. 
Normalement j'ai pu fixé ça en fixant les tailles des crop demandé par le Core afin qu'il reste dans l'image.
