### ISSUE TITLE
Search engine (image, annotations & all)

### ISSUE THREAD

**Issue by stevben** [cytomine/Cytomine-core-legacy#1053]
Développer un search engine basé sur notre moteur de recherche.
Il faudrait pouvoir le faire au niveau global mais aussi au niveau projet (rechercher images dont les metadonnées X/Y sont présentes)

**Comment by loic911** [comment]
Est-ce qu'ils font parfois des recherches complexes? (mémoriser les filtres)

**Comment by stevben** [comment]
non pas de recherche complexe (faisons le LEAN), juste un mot ou plusieurs mots séparés par des espaces
