### ISSUE TITLE
Uri too large

### ISSUE THREAD

**Issue by loic911** [cytomine/Cytomine-core-legacy#1056]
Some crop on annotation trigger 414 "uri too large":

http://image.cytomine.be/image/crop.png?fif=%2Fdata%2Fbeta.cytomine.be%2F14%2F14%2F1350547488518%2FPGP_POUMON_PGP10_1_-_2012-08-07_12.44.21.jp2&mimeType=image/jp2&topLeftX=7524&topLeftY=5084&width=188&height=328&imageWidth=34816&imageHeight=28416&draw=true&location=POLYGON+%28%287524.022023715259+5004.022023715259%2C+7524+5004.245634248852%2C+7524+5015.754365751148%2C+7524.023244565544+5015.990371785701%2C+7524.173689643053+5016.173689643053%2C+7527.826310356947+5019.826310356947%2C+7528.009628214299+5019.976755434456%2C+7528.245634248852+5020%2C+7535.754365751148+5020%2C+7535.987715367351+5019.977017068827%2C+7536.134947733186+5019.797613911976%2C+7536.8280335791815+5019.104528065981%2C+7537.64301631587+5018.559974011053%2C+7538.548576613728+5018.184878654134%2C+7539.509914298352+5017.993656699434%2C+7540.490085701648+5017.993656699434%2C+7541.451423386272+5018.184878654134%2C+7542.35698368413+5018.559974011053%2C+7543.1719664208185+5019.104528065981%2C+7543.865052266814+5019.797613911976%2C+7544.017106936693+5019.982893063307%2C+7544.202386088024+5020.134947733186%2C+7544.895471934019+5020.8280335791815%2C+7545.440025988947+5021.64301631587%2C+7545.815121345866+5022.548576613728%2C+7546.006343300566+5023.509914298352%2C+7546.006343300566+5024.490085701648%2C+7545.815121345866+5025.451423386272%2C+7545.440025988947+5026.35698368413%2C+7544.895471934019+5027.1719664208185%2C+7544.202386088024+5027.865052266814%2C+7543.826310356942+5028.173689643058%2C+7540.173689643053+5031.826310356947%2C+7540.023244565544+5032.009628214299%2C+7540+5032.245634248852%2C+7540+5067.754365751148%2C+7540.022023715259+5067.977976284741%2C+7540.245634248852+5068%2C+7549.928932188135+5068%2C+7550.904383798215+5068.096073597984%2C+7551.84234934996+5068.380602337444%2C+7552.706783353233+5068.8426519384875%2C+7553.464466094068+5069.464466094068%2C+7554.535533905932+5070.535533905932%2C+7555.1573480615125+5071.293216646767%2C+7555.619397662556+5072.15765065004%2C+7555.903926402016+5073.095616201785%2C+7556+5074.071067811865%2C+7556+5075.754365751148%2C+7556.022023715259+5075.977976284741%2C+7556.245634248852+5076%2C+7557.928932188135+5076%2C+7558.904383798215+5076.096073597984%2C+7559.84234934996+5076.380602337444%2C+7560.706783353233+5076.8426519384875%2C+7561.464466094068+5077.464466094068%2C+7567.826310356947+5083.826310356947%2C+7568.009628214299+5083.976755434456%2C+7568.245634248852+5084%2C+7599.754365751148+5084%2C+7599.990371785701+5083.976755434456%2C+7600.173689643053+5083.826310356947%2C+7602.535533905932+5081.464466094068%2C+7603.293216646767+5080.8426519384875%2C+7604.15765065004+5080.380602337444%2C+7605.095616201785+5080.096073597984%2C+7606.071067811865+5080%2C+7611.754365751148+5080%2C+7611.977976284741+5079.977976284741%2C+7612+5079.754365751148%2C+7612+5078.071067811865%2C+7612.096073597984+5077.095616201785%2C+7612.380602337444+5076.15765065004%2C+7612.8426519384875+5075.293216646767%2C+7613.464466094068+5074.535533905932%2C+7618.535533905932+5069.464466094068%2C+7619.293216646767+5068.8426519384875%2C+7620.15765065004+5068.380602337444%2C+7621.095616201785+5068.096073597984%2C+7622.071067811865+5068%2C+7623.754365751148+5068%2C+7623.977976284741+5067.977976284741%2C+7624+5067.754365751148%2C+7624+5056.245634248852%2C+7623.977976284741+5056.022023715259%2C+7623.754365751148+5056%2C+7622.071067811865+5056%2C+7621.095616201785+5055.903926402016%2C+7620.15765065004+5055.619397662556%2C+7619.293216646767+5055.1573480615125%2C+7618.535533905932+5054.535533905932%2C+7617.464466094068+5053.464466094068%2C+7616.8426519384875+5052.706783353233%2C+7616.380602337444+5051.84234934996%2C+7616.096073597984+5050.904383798215%2C+7616+5049.928932188135%2C+7616+5028.245634248852%2C+7615.977017068827+5028.012284632649%2C+7615.797613911976+5027.865052266814%2C+7615.104528065981+5027.1719664208185%2C+7614.559974011053+5026.35698368413%2C+7614.184878654134+5025.451423386272%2C+7613.993656699434+5024.490085701648%2C+7613.993656699434+5023.509914298352%2C+7614.184878654134+5022.548576613728%2C+7614.559974011053+5021.64301631587%2C+7615.104528065981+5020.8280335791815%2C+7615.797613911976+5020.134947733186%2C+7615.977017068827+5019.987715367351%2C+7616+5019.754365751148%2C+7616+5008.245634248852%2C+7615.976755434456+5008.009628214299%2C+7615.826310356947+5007.826310356947%2C+7613.535533905932+5005.535533905932%2C+7612.913719750352+5004.777851165098%2C+7612.4516701493085+5003.913417161825%2C+7612.167141409849+5002.97545161008%2C+7612.071067811865+5002%2C+7612.167141409849+5001.02454838992%2C+7612.4516701493085+5000.086582838175%2C+7612.913719750352+4999.222148834902%2C+7613.535533905932+4998.464466094068%2C+7615.826310356947+4996.173689643053%2C+7615.978350552223+4995.988428129078%2C+7616.111778050684+4995.54857661373%2C+7616.45425154945+4994.705090677664%2C+7616.943986088984+4993.937681593482%2C+7617.564746839585+4993.271789175585%2C+7618.29595541795+4992.729487934002%2C+7619.113372066034+4992.3287552985275%2C+7619.989899205444+4992.0828756621695%2C+7620.896479729346+4992%2C+7623.754365751148+4992%2C+7623.977976284741+4991.977976284741%2C+7624+4991.754365751148%2C+7624+4982.071067811865%2C+7624.096073597984+4981.095616201785%2C+7624.380602337444+4980.15765065004%2C+7624.8426519384875+4979.293216646767%2C+7625.464466094068+4978.535533905932%2C+7626.535533905932+4977.464466094068%2C+7627.293216646767+4976.8426519384875%2C+7628.15765065004+4976.380602337444%2C+7629.095616201785+4976.096073597984%2C+7630.071067811865+4976%2C+7631.754365751148+4976%2C+7631.977976284741+4975.977976284741%2C+7632+4975.754365751148%2C+7632+4970.071067811865%2C+7632.096073597984+4969.095616201785%2C+7632.380602337444+4968.15765065004%2C+7632.8426519384875+4967.293216646767%2C+7633.464466094068+4966.535533905932%2C+7634.535533905932+4965.464466094068%2C+7635.293216646767+4964.8426519384875%2C+7636.15765065004+4964.380602337444%2C+7637.095616201785+4964.096073597984%2C+7638.071067811865+4964%2C+7647.754365751148+4964%2C+7647.977976284741+4963.977976284741%2C+7648+4963.754365751148%2C+7648+4962.071067811865%2C+7648.096073597984+4961.095616201785%2C+7648.380602337444+4960.15765065004%2C+7648.8426519384875+4959.293216646767%2C+7649.464466094068+4958.535533905932%2C+7650.535533905932+4957.464466094068%2C+7651.293216646767+4956.8426519384875%2C+7652.15765065004+4956.380602337444%2C+7653.095616201785+4956.096073597984%2C+7654.071067811865+4956%2C+7659.754365751148+4956%2C+7659.990371785701+4955.976755434456%2C+7660.173689643053+4955.826310356947%2C+7663.826310356947+4952.173689643053%2C+7663.976755434456+4951.990371785701%2C+7664+4951.754365751148%2C+7664+4950.071067811865%2C+7664.096073597984+4949.095616201785%2C+7664.380602337444+4948.15765065004%2C+7664.8426519384875+4947.293216646767%2C+7665.464466094068+4946.535533905932%2C+7666.535533905932+4945.464466094068%2C+7667.293216646767+4944.8426519384875%2C+7668.15765065004+4944.380602337444%2C+7669.095616201785+4944.096073597984%2C+7670.071067811865+4944%2C+7679.754365751148+4944%2C+7679.990371785701+4943.976755434456%2C+7680.173689643053+4943.826310356947%2C+7682.535533905932+4941.464466094068%2C+7683.293216646767+4940.8426519384875%2C+7684.15765065004+4940.380602337444%2C+7685.095616201785+4940.096073597984%2C+7686.071067811865+4940%2C+7695.754365751148+4940%2C+7695.977976284741+4939.977976284741%2C+7696+4939.754365751148%2C+7696+4934.071067811865%2C+7696.096073597984+4933.095616201785%2C+7696.380602337444+4932.15765065004%2C+7696.8426519384875+4931.293216646767%2C+7697.464466094068+4930.535533905932%2C+7698.535533905932+4929.464466094068%2C+7699.293216646767+4928.8426519384875%2C+7700.15765065004+4928.380602337444%2C+7701.095616201785+4928.096073597984%2C+7702.071067811865+4928%2C+7711.754365751148+4928%2C+7711.977976284741+4927.977976284741%2C+7712+4927.754365751148%2C+7712+4892.245634248852%2C+7711.976755434456+4892.009628214299%2C+7711.826310356947+4891.826310356947%2C+7709.464466094068+4889.464466094068%2C+7708.8426519384875+4888.706783353233%2C+7708.380602337444+4887.84234934996%2C+7708.096073597984+4886.904383798215%2C+7708+4885.928932188135%2C+7708+4884.245634248852%2C+7707.977976284741+4884.022023715259%2C+7707.754365751148+4884%2C+7702.071067811865+4884%2C+7701.095616201785+4883.903926402016%2C+7700.15765065004+4883.619397662556%2C+7699.293216646767+4883.1573480615125%2C+7698.535533905932+4882.535533905932%2C+7697.464466094068+4881.464466094068%2C+7696.8426519384875+4880.706783353233%2C+7696.380602337444+4879.84234934996%2C+7696.096073597984+4878.904383798215%2C+7696+4877.928932188135%2C+7696+4868.245634248852%2C+7695.977976284741+4868.022023715259%2C+7695.754365751148+4868%2C+7690.071067811865+4868%2C+7689.095616201785+4867.903926402016%2C+7688.15765065004+4867.619397662556%2C+7687.293216646767+4867.1573480615125%2C+7686.535533905932+4866.535533905932%2C+7684.173689643053+4864.173689643053%2C+7683.990371785701+4864.023244565544%2C+7683.50991429835+4863.975923633361%2C+7683.512237847416+4863.952332243785%2C+7682.955855604143+4863.895025321881%2C+7681.979471205013+4863.584509160742%2C+7681.08688028212+4863.081490050209%2C+7680.315562613392+4862.407089697969%2C+7679.697905728432+4861.589626087983%2C+7679.259844960311+4860.663424411982%2C+7679.019774424285+4859.6673757590925%2C+7678.987774651249+4858.643304084005%2C+7679.165189307555+4857.634210024504%2C+7679.544568774627+4856.682465310225%2C+7679.874036484147+4856.184586633139%2C+7679.976508980268+4855.99287407707%2C+7680+4855.754365751148%2C+7680+4852.245634248852%2C+7679.977976284741+4852.022023715259%2C+7679.754365751148+4852%2C+7678.071067811865+4852%2C+7677.095616201785+4851.903926402016%2C+7676.15765065004+4851.619397662556%2C+7675.293216646767+4851.1573480615125%2C+7674.535533905932+4850.535533905932%2C+7673.464466094068+4849.464466094068%2C+7672.8426519384875+4848.706783353233%2C+7672.380602337444+4847.84234934996%2C+7672.096073597984+4846.904383798215%2C+7672+4845.928932188135%2C+7672+4844.245634248852%2C+7671.980454623665+4844.04718671263%2C+7671.826310356947+4844.173689643053%2C+7664.173689643053+4851.826310356947%2C+7664.023244565544+4852.009628214299%2C+7664+4852.245634248852%2C+7664+4859.754365751148%2C+7664.023491019732+4859.99287407707%2C+7664.125963515853+4860.184586633139%2C+7664.455431225373+4860.682465310225%2C+7664.834810692445+4861.634210024504%2C+7665.012225348751+4862.643304084005%2C+7664.980225575715+4863.6673757590925%2C+7664.740155039689+4864.663424411982%2C+7664.302094271568+4865.589626087983%2C+7663.684437386608+4866.407089697969%2C+7662.91311971788+4867.081490050209%2C+7662.020528794987+4867.584509160742%2C+7661.044144395857+4867.895025321881%2C+7660.024964775699+4868%2C+7654.071067811865+4868%2C+7653.095616201785+4867.903926402016%2C+7652.15765065004+4867.619397662556%2C+7651.293216646767+4867.1573480615125%2C+7650.535533905932+4866.535533905932%2C+7649.464466094068+4865.464466094068%2C+7648.8426519384875+4864.706783353233%2C+7648.380602337444+4863.84234934996%2C+7648.096073597984+4862.904383798215%2C+7648+4861.928932188135%2C+7648+4852.245634248852%2C+7647.977976284741+4852.022023715259%2C+7647.754365751148+4852%2C+7623.975035224301+4852%2C+7622.955855604143+4851.895025321881%2C+7621.979471205013+4851.584509160742%2C+7621.08688028212+4851.081490050209%2C+7620.315562613392+4850.407089697969%2C+7619.697905728432+4849.589626087983%2C+7619.259844960311+4848.663424411982%2C+7619.019774424285+4847.6673757590925%2C+7618.987774651249+4846.643304084005%2C+7619.165189307555+4845.634210024504%2C+7619.544568774627+4844.682465310225%2C+7619.874036484147+4844.184586633139%2C+7619.976508980268+4843.99287407707%2C+7620+4843.754365751148%2C+7620+4840.245634248852%2C+7619.977976284741+4840.022023715259%2C+7619.754365751148+4840%2C+7604.245634248852+4840%2C+7604.022023715259+4840.022023715259%2C+7604+4840.245634248852%2C+7604+4856.024964775699%2C+7603.895025321881+4857.044144395857%2C+7603.584509160742+4858.020528794987%2C+7603.081490050209+4858.91311971788%2C+7602.407089697969+4859.684437386608%2C+7601.589626087983+4860.302094271568%2C+7600.663424411982+4860.740155039689%2C+7599.6673757590925+4860.980225575715%2C+7598.643304084005+4861.012225348751%2C+7597.634210024504+4860.834810692445%2C+7596.682465310225+4860.455431225373%2C+7596.184586633139+4860.125963515853%2C+7595.99287407707+4860.023491019732%2C+7595.754365751148+4860%2C+7594.071067811865+4860%2C+7593.095616201785+4859.903926402016%2C+7592.15765065004+4859.619397662556%2C+7591.293216646767+4859.1573480615125%2C+7590.535533905932+4858.535533905932%2C+7584.173689643053+4852.173689643053%2C+7583.990371785701+4852.023244565544%2C+7583.754365751148+4852%2C+7578.071067811865+4852%2C+7577.095616201785+4851.903926402016%2C+7576.15765065004+4851.619397662556%2C+7575.293216646767+4851.1573480615125%2C+7574.535533905932+4850.535533905932%2C+7573.464466094068+4849.464466094068%2C+7572.8426519384875+4848.706783353233%2C+7572.380602337444+4847.84234934996%2C+7572.096073597984+4846.904383798215%2C+7572+4845.928932188135%2C+7572+4844.245634248852%2C+7571.976755434456+4844.009628214299%2C+7571.826310356947+4843.826310356947%2C+7569.464466094068+4841.464466094068%2C+7568.8426519384875+4840.706783353233%2C+7568.380602337444+4839.84234934996%2C+7568.096073597984+4838.904383798215%2C+7568+4837.928932188135%2C+7568+4830.071067811865%2C+7568.096073597984+4829.095616201785%2C+7568.380602337444+4828.15765065004%2C+7568.8426519384875+4827.293216646767%2C+7569.464466094068+4826.535533905932%2C+7570.535533905932+4825.464466094068%2C+7571.293216646767+4824.8426519384875%2C+7572.15765065004+4824.380602337444%2C+7573.095616201785+4824.096073597984%2C+7574.071067811865+4824%2C+7575.754365751148+4824%2C+7575.977976284741+4823.977976284741%2C+7576+4823.754365751148%2C+7576+4822.071067811865%2C+7576.096073597984+4821.095616201785%2C+7576.380602337444+4820.15765065004%2C+7576.8426519384875+4819.293216646767%2C+7577.464466094068+4818.535533905932%2C+7578.535533905932+4817.464466094068%2C+7579.293216646767+4816.8426519384875%2C+7580.15765065004+4816.380602337444%2C+7581.095616201785+4816.096073597984%2C+7582.071067811865+4816%2C+7597.928932188135+4816%2C+7598.904383798215+4816.096073597984%2C+7599.84234934996+4816.380602337444%2C+7600.706783353233+4816.8426519384875%2C+7601.464466094068+4817.464466094068%2C+7602.535533905932+4818.535533905932%2C+7603.1573480615125+4819.293216646767%2C+7603.619397662556+4820.15765065004%2C+7603.903926402016+4821.095616201785%2C+7604+4822.071067811865%2C+7604+4823.754365751148%2C+7604.022023715259+4823.977976284741%2C+7604.245634248852+4824%2C+7615.754365751148+4824%2C+7615.977976284741+4823.977976284741%2C+7616+4823.754365751148%2C+7616+4822.071067811865%2C+7616.096073597984+4821.095616201785%2C+7616.380602337444+4820.15765065004%2C+7616.8426519384875+4819.293216646767%2C+7617.464466094068+4818.535533905932%2C+7618.535533905932+4817.464466094068%2C+7619.293216646767+4816.8426519384875%2C+7620.15765065004+4816.380602337444%2C+7621.095616201785+4816.096073597984%2C+7622.071067811865+4816%2C+7663.754365751148+4816%2C+7663.977976284741+4815.977976284741%2C+7664+4815.754365751148%2C+7664+4812.245634248852%2C+7663.977976284741+4812.022023715259%2C+7663.754365751148+4812%2C+7662.071067811865+4812%2C+7661.095616201785+4811.903926402016%2C+7660.15765065004+4811.619397662556%2C+7659.293216646767+4811.1573480615125%2C+7658.535533905932+4810.535533905932%2C+7657.464466094068+4809.464466094068%2C+7656.8426519384875+4808.706783353233%2C+7656.380602337444+4807.84234934996%2C+7656.096073597984+4806.904383798215%2C+7656+4805.928932188135%2C+7656+4804.245634248852%2C+7655.977976284741+4804.022023715259%2C+7655.754365751148+4804%2C+7654.071067811865+4804%2C+7653.095616201785+4803.903926402016%2C+7652.15765065004+4803.619397662556%2C+7651.293216646767+4803.1573480615125%2C+7650.535533905932+4802.535533905932%2C+7648.173689643053+4800.173689643053%2C+7647.990371785701+4800.023244565544%2C+7647.754365751148+4800%2C+7646.071067811865+4800%2C+7645.095616201785+4799.903926402016%2C+7644.15765065004+4799.619397662556%2C+7643.293216646767+4799.1573480615125%2C+7642.535533905932+4798.535533905932%2C+7636.535533905932+4792.535533905932%2C+7635.913719750352+4791.777851165098%2C+7635.4516701493085+4790.913417161825%2C+7635.167141409849+4789.97545161008%2C+7635.071067811865+4789%2C+7635.167141409849+4788.02454838992%2C+7635.4516701493085+4787.086582838175%2C+7635.913719750352+4786.222148834902%2C+7636.535533905932+4785.464466094068%2C+7637.293216646767+4784.8426519384875%2C+7638.15765065004+4784.380602337444%2C+7639.095616201785+4784.096073597984%2C+7640.071067811865+4784%2C+7647.754365751148+4784%2C+7647.977976284741+4783.977976284741%2C+7648+4783.754365751148%2C+7648+4776.245634248852%2C+7647.977976284741+4776.022023715259%2C+7647.754365751148+4776%2C+7638.071067811865+4776%2C+7637.095616201785+4775.903926402016%2C+7636.15765065004+4775.619397662556%2C+7635.293216646767+4775.1573480615125%2C+7634.535533905932+4774.535533905932%2C+7632.173689643053+4772.173689643053%2C+7631.990371785701+4772.023244565544%2C+7631.754365751148+4772%2C+7626.071067811865+4772%2C+7625.095616201785+4771.903926402016%2C+7624.15765065004+4771.619397662556%2C+7623.293216646767+4771.1573480615125%2C+7622.535533905932+4770.535533905932%2C+7621.464466094068+4769.464466094068%2C+7620.8426519384875+4768.706783353233%2C+7620.380602337444+4767.84234934996%2C+7620.096073597984+4766.904383798215%2C+7620+4765.928932188135%2C+7620+4764.245634248852%2C+7619.976755434456+4764.009628214299%2C+7619.826310356947+4763.826310356947%2C+7617.464466094068+4761.464466094068%2C+7616.8426519384875+4760.706783353233%2C+7616.380602337444+4759.84234934996%2C+7616.096073597984+4758.904383798215%2C+7616+4757.928932188135%2C+7616+4756.245634248852%2C+7615.977976284741+4756.022023715259%2C+7615.754365751148+4756%2C+7612.245634248852+4756%2C+7612.009628214299+4756.023244565544%2C+7611.826310356947+4756.173689643053%2C+7608.529161922954+4759.470838077046%2C+7607.734264795542+4760.117278590957%2C+7606.824288682664+4760.588118537416%2C+7605.837443364137+4760.863587407695%2C+7604.815166347827+4760.932118299399%2C+7603.80038291403+4760.790833609207%2C+7602.835703688474+4760.44566586307%2C+7601.961635427636+4759.911108610207%2C+7601.21488014525+4759.209607840841%2C+7600.626793999479+4758.370619481957%2C+7600.222070651863+4757.429372546723%2C+7600.01770438366+4756.425389872763%2C+7599.977976284741+4756.022023715259%2C+7599.754365751148+4756%2C+7560.245634248852+4756%2C+7560.009628214299+4756.023244565544%2C+7559.826310356947+4756.173689643053%2C+7556.173689643053+4759.826310356947%2C+7556.023244565544+4760.009628214299%2C+7556+4760.245634248852%2C+7556+4765.928932188135%2C+7555.903926402016+4766.904383798215%2C+7555.619397662556+4767.84234934996%2C+7555.1573480615125+4768.706783353233%2C+7554.535533905932+4769.464466094068%2C+7552.173689643053+4771.826310356947%2C+7552.023244565544+4772.009628214299%2C+7552+4772.245634248852%2C+7552+4783.754365751148%2C+7552.023244565544+4783.990371785701%2C+7552.173689643053+4784.173689643053%2C+7554.535533905932+4786.535533905932%2C+7555.1573480615125+4787.293216646767%2C+7555.619397662556+4788.15765065004%2C+7555.903926402016+4789.095616201785%2C+7556+4790.071067811865%2C+7556+4813.928932188135%2C+7555.903926402016+4814.904383798215%2C+7555.619397662556+4815.84234934996%2C+7555.1573480615125+4816.706783353233%2C+7554.535533905932+4817.464466094068%2C+7552.173689643053+4819.826310356947%2C+7552.023244565544+4820.009628214299%2C+7552+4820.245634248852%2C+7552+4831.754365751148%2C+7552.023244565544+4831.990371785701%2C+7552.173689643053+4832.173689643053%2C+7554.464466094068+4834.464466094068%2C+7555.086280249648+4835.222148834902%2C+7555.5483298506915+4836.086582838175%2C+7555.832858590151+4837.02454838992%2C+7555.928932188135+4838%2C+7555.832858590151+4838.97545161008%2C+7555.5483298506915+4839.913417161825%2C+7555.086280249648+4840.777851165098%2C+7554.464466094068+4841.535533905932%2C+7552.173689643053+4843.826310356947%2C+7552.023244565544+4844.009628214299%2C+7552+4844.245634248852%2C+7552+4847.754365751148%2C+7552.023244565544+4847.990371785701%2C+7552.173689643053+4848.173689643053%2C+7554.535533905932+4850.535533905932%2C+7555.1573480615125+4851.293216646767%2C+7555.619397662556+4852.15765065004%2C+7555.903926402016+4853.095616201785%2C+7556+4854.071067811865%2C+7556+4863.754365751148%2C+7556.023244565544+4863.990371785701%2C+7556.173689643053+4864.173689643053%2C+7556.464466094068+4864.464466094068%2C+7557.086280249648+4865.222148834902%2C+7557.5483298506915+4866.086582838175%2C+7557.832858590151+4867.02454838992%2C+7557.928932188135+4868%2C+7557.832858590151+4868.97545161008%2C+7557.5483298506915+4869.913417161825%2C+7557.086280249648+4870.777851165098%2C+7556.464466094068+4871.535533905932%2C+7556.173689643053+4871.826310356947%2C+7556.023244565544+4872.009628214299%2C+7556+4872.245634248852%2C+7556+4879.754365751148%2C+7556.022023715259+4879.977976284741%2C+7556.245634248852+4880%2C+7565.928932188135+4880%2C+7566.904383798215+4880.096073597984%2C+7567.84234934996+4880.380602337444%2C+7568.706783353233+4880.8426519384875%2C+7569.464466094068+4881.464466094068%2C+7570.535533905932+4882.535533905932%2C+7571.1573480615125+4883.293216646767%2C+7571.619397662556+4884.15765065004%2C+7571.903926402016+4885.095616201785%2C+7572+4886.071067811865%2C+7572+4911.754365751148%2C+7572.022023715259+4911.977976284741%2C+7572.245634248852+4912%2C+7577.928932188135+4912%2C+7578.904383798215+4912.096073597984%2C+7579.84234934996+4912.380602337444%2C+7580.706783353233+4912.8426519384875%2C+7581.464466094068+4913.464466094068%2C+7583.470838077046+4915.470838077046%2C+7584.117278590957+4916.265735204458%2C+7584.588118537416+4917.175711317336%2C+7584.863587407695+4918.162556635863%2C+7584.932118299399+4919.184833652173%2C+7584.790833609207+4920.19961708597%2C+7584.44566586307+4921.164296311526%2C+7583.911108610207+4922.038364572364%2C+7583.209607840841+4922.78511985475%2C+7582.370619481957+4923.373206000521%2C+7581.429372546723+4923.777929348137%2C+7580.425389872763+4923.98229561634%2C+7580.022023715259+4924.022023715259%2C+7580+4924.245634248852%2C+7580+4927.754365751148%2C+7580.022023715259+4927.977976284741%2C+7580.245634248852+4928%2C+7581.928932188135+4928%2C+7582.904383798215+4928.096073597984%2C+7583.84234934996+4928.380602337444%2C+7584.706783353233+4928.8426519384875%2C+7585.464466094068+4929.464466094068%2C+7586.535533905932+4930.535533905932%2C+7587.1573480615125+4931.293216646767%2C+7587.619397662556+4932.15765065004%2C+7587.903926402016+4933.095616201785%2C+7588+4934.071067811865%2C+7588+4943.754365751148%2C+7588.022023715259+4943.977976284741%2C+7588.245634248852+4944%2C+7593.928932188135+4944%2C+7594.904383798215+4944.096073597984%2C+7595.84234934996+4944.380602337444%2C+7596.706783353233+4944.8426519384875%2C+7597.464466094068+4945.464466094068%2C+7598.464466094068+4946.464466094068%2C+7599.086280249648+4947.222148834902%2C+7599.5483298506915+4948.086582838175%2C+7599.832858590151+4949.02454838992%2C+7599.928932188135+4950%2C+7599.832858590151+4950.97545161008%2C+7599.5483298506915+4951.913417161825%2C+7599.086280249648+4952.777851165098%2C+7598.464466094068+4953.535533905932%2C+7597.464466094068+4954.535533905932%2C+7596.706783353233+4955.1573480615125%2C+7595.84234934996+4955.619397662556%2C+7594.904383798215+4955.903926402016%2C+7593.928932188135+4956%2C+7592.245634248852+4956%2C+7592.009628214299+4956.023244565544%2C+7591.826310356947+4956.173689643053%2C+7588.173689643053+4959.826310356947%2C+7588.023244565544+4960.009628214299%2C+7588+4960.245634248852%2C+7588+4961.928932188135%2C+7587.903926402016+4962.904383798215%2C+7587.619397662556+4963.84234934996%2C+7587.1573480615125+4964.706783353233%2C+7586.535533905932+4965.464466094068%2C+7584.173689643053+4967.826310356947%2C+7584.023244565544+4968.009628214299%2C+7584+4968.245634248852%2C+7584+4973.928932188135%2C+7583.903926402016+4974.904383798215%2C+7583.619397662556+4975.84234934996%2C+7583.1573480615125+4976.706783353233%2C+7582.535533905932+4977.464466094068%2C+7581.464466094068+4978.535533905932%2C+7580.706783353233+4979.1573480615125%2C+7579.84234934996+4979.619397662556%2C+7578.904383798215+4979.903926402016%2C+7577.928932188135+4980%2C+7572.245634248852+4980%2C+7572.022023715259+4980.022023715259%2C+7572+4980.245634248852%2C+7572+4987%2C+7571.903926402016+4987.97545161008%2C+7571.619397662556+4988.913417161825%2C+7571.1573480615125+4989.777851165098%2C+7570.535533905932+4990.535533905932%2C+7569.777851165098+4991.1573480615125%2C+7568.913417161825+4991.619397662556%2C+7567.97545161008+4991.903926402016%2C+7567+4992%2C+7544.245634248852+4992%2C+7544.009628214299+4992.023244565544%2C+7543.826310356947+4992.173689643053%2C+7540.173689643053+4995.826310356947%2C+7540.023244565544+4996.009628214299%2C+7540+4996.245634248852%2C+7540+4997.928932188135%2C+7539.903926402016+4998.904383798215%2C+7539.619397662556+4999.84234934996%2C+7539.1573480615125+5000.706783353233%2C+7538.535533905932+5001.464466094068%2C+7535.535533905932+5004.464466094068%2C+7534.777851165098+5005.086280249648%2C+7533.913417161825+5005.5483298506915%2C+7532.97545161008+5005.832858590151%2C+7532+5005.928932188135%2C+7531.02454838992+5005.832858590151%2C+7530.086582838175+5005.5483298506915%2C+7529.222148834902+5005.086280249648%2C+7528.464466094068+5004.464466094068%2C+7528.173689643053+5004.173689643053%2C+7527.990371785701+5004.023244565544%2C+7527.754365751148+5004%2C+7524.245634248852+5004%2C+7524.022023715259+5004.022023715259%29%29

**Comment by stevben** [comment]
Je crains qu'il faille passer cela en POST avec la géométrie dans le BODY

**Comment by loic911** [comment]
Ca n'est pas dérangeant et c'est même plus cohérent. 
Un GET récupère une ressource qui existe déjà (ce qui n'est pas le cas ici).
Un POST fournit des infos pour créer une ressource et pour éventuellement la récupérer après création (ce qui est finalement le cas ici)

**Comment by stevben** [comment]
Je suis d'accord avec toi, bien que la ressource créée ne soit pas stockée (mais elle le pourrait). Le seul soucis, c'est que tu ne peux faire de redirection HTTP avec la method POST car les browsers font un GET sur le location quand il reçoit un redirect 301 ou 302. Il faudrait donc que le client fasse sa requête directement sur l'image serveur. Ca impliquerait de déplacer l'intelligence (qui génère l'URL vers l'IMS) du CORE dans le client.

**Comment by stevben** [comment]
http://www.alanflavell.org.uk/www/post-redirect.html

The simplest situations on the WWW are "idempotent" transactions, i.e those which can be repeated without causing any harm. These are typically "GET" transactions, either because they are retrieval of straightforward URL references (e.g href= or src= attributes in HTML), or because they are form submissions using the GET method. Redirecting a transaction of that kind is straightforward, and no questions asked: the client receives the redirection response, including a Location: header that specifies the new URL, and the client reacts to it by re-issuing the transaction to the new URL. There's a difference between the different 30x status codes associated with these redirections in their implied cacheability, but otherwise they are basically similar (301 and 302) in response to GET requests.

POST transactions are different, since they are defined to be, in principle, non-idempotent (such as ordering a pizza, casting a vote or whatever) and mustn't be arbitrarily repeated.

The HTTP protocol specifications are designed to take this distinction into account: the GET method is defined to be inherently idempotent, whereas the POST method is defined to be, at least potentially, non-idempotent; the specifications call for a number of precautions to be taken by client agents (such as browsers) for protecting users against inadvertently (re)submitting a POST transaction which they had not intended, or submitting a POST into a context which they would not have wanted.

**Comment by stevben** [comment]
Le plus simple à mon avis, c'est de ne plus faire le redirect côté CORE mais de renvoyer un JSON avec l'URL et les paramètres à soumettre au POST. Le client contacte donc l'IMS directement dans un second temps.

**Comment by loic911** [comment]
J'ai fais au plus simple pour pas bousiller toute l'architecture et mettre a jour tous les clients.
Les polygones sont simplifié puis passé en param de l'URL.
Le seul problème pourrait être pour les mask qui seront moins précis.
