### ISSUE TITLE
Dashboard graph style

### ISSUE THREAD

**Issue by rmaree** [cytomine/Cytomine-core-legacy#1060]
Graphs/plots are all crushed or wizened (écrasés/ratatinés) e.g. http://beta.cytomine.be/#tabs-dashboard-86501585  they only occupies 10% of the screen width

**Comment by loic911** [comment]
Cannot reproduce

**Comment by rmaree** [comment]
With google chrome version 25 & 31: OK
With  newer version 35: not OK
With firefox version 31: not OK

![dashbug](https://cloud.githubusercontent.com/assets/3587894/3950009/aeca3dce-26be-11e4-81d7-7f3196b60e2c.png)
