### ISSUE TITLE
Test all crop/mask services

### ISSUE THREAD

**Issue by rmaree** [cytomine/Cytomine-core-legacy#1061]
We should check that all annotation crop/mask services are still working (crop, alpha, reviewed true/false, per single term, big polygon annotations,...) both at the server side and client side (java/python).

e.g. http://beta.cytomine.be/api/userannotation/95189319/crop.png   is working in web client but not in python/java because of redirections ? header signatures ?
In Python It is not enough to add this in fetch_url function:
con.follow_redirects = True 
con.follow_all_redirects = True

The request returns:

> > > > > > <html><head><title>Apache Tomcat/7.0.30 - Rapport
> > > > > > d''erreur</title><style></style>
> > > > > > </head><body><h1>Etat HTTP 401 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Rapport d''Ã©tat</p><p><b>message</b> <u></u></p><p><b>description</b> <u>La requÃªte nÃ©cessite une authentification HTTP.</u></p><HR size="1"
> > > > > > noshade="noshade"><h3>Apache Tomcat/7.0.30</h3></body></html>

**Comment by rmaree** [comment]
Previous error is solved.

This crop works:
http://beta.cytomine.be/api/userannotation/26856187/crop.png

But not the alphamask:
http://beta.cytomine.be/api/userannotation/26856187/alphamask.png
http://beta.cytomine.be/api/userannotation/26856187/crop.png?alphaMask=true

It generates the following url:

http://image2.cytomine.be/image/crop.png?fif=%2Fdata%2Fbeta.cytomine.be%2F14%2F14%2F1372256045905%2FREIN_R568_290513_PCNA_20_06_-_2013-06-25_13.08.22.ndpi.svs&mimeType=openslide/svs&topLeftX=6257&topLeftY=14558&width=25&height=25&imageWidth=19200&imageHeight=22528&alphaMask=true&location=POLYGON+%28%286278+14556%2C+6281.375730091899+14551.88156143182%2C+6282.784493105645+14546.74614745977%2C+6281.982701117951+14541.481717813389%2C+6279.108991247542+14536.998540204377%2C+6274.660254037844+14534.071796769724%2C+6269.405716567925+14533.20754803791%2C+6264.253936102307+14534.55523046612%2C+6260.095702285952+14537.881817519205%2C+6257.650011522076+14542.61211207459%2C+6257.339745962156+14547.928203230276%2C+6259.218553340176+14552.91089053027%2C+6262.961570792048+14556.698622074111%2C+6267.921596596097+14558.636464667408%2C+6273.240997230383+14558.389347721033%2C+6278+14556%29%29&resolution=0.4549280107021332

that returns a error 500:

Error 500: Internal Server Error
URI
/image/crop.png
Class
java.awt.HeadlessException
Message
null
Trace
    Line | Method
->>  207 | checkHeadless in java.awt.GraphicsEnvironment

---

|    535 | <init>        in java.awt.Window
|    420 | <init> . . .  in java.awt.Frame
|     61 | <init>        in ij.gui.ImageWindow
|     57 | <init> . . .  in     ''
|    367 | show          in ij.ImagePlus
|    343 | show . . . .  in     ''
|    172 | crop          in be.cytomine.image.ImageController
|   1145 | runWorker . . in java.util.concurrent.ThreadPoolExecutor
|    615 | run           in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run . . . . . in java.lang.Thread

**Comment by stevben** [comment]
FIX 1 (bad) : virer le headless dans l'environnement de prod
FIX 2 (good) : inclure headless.jar avec imagej.jar ou passer à FIJI ou se passer d'imageJ

**Comment by stevben** [comment]
Fixé. Il y avait un ImagePlus.show() qui trainait et qui provoquait l'exception.
C'est déployé.

**Comment by rmaree** [comment]
In the past, we were able to generate a mask (according e.g. to the review layer) for a tile using this kind of url:
http://beta.cytomine.be/api/imageinstance/7889452/mask.png?x=10000&y=10000&w=1500&h=1500&review=true

Now according to ImageServerAPI.groovy we should be able to do it using first this to get the url:
http://beta.cytomine.be/api/imageinstance/7889452/window_url-10000-10000-1500-1500.jpg?mask=true?reviewed=true

which returns:
http://beta.cytomine.be/api/abstractimage/7889365/crop.png?topLeftX=10000&topLeftY=19440&width=1500&height=1500&imageWidth=34816&imageHeight=29440&mask=true%3Freviewed%3Dtrue

but this url returns the following error:
Error 500: Internal Server Error
URI
/image/crop.png
Class
groovy.lang.GroovyRuntimeException
Message
Ambiguous method overloading for method com.vividsolutions.jts.io.WKTReader#read. Cannot resolve which method to invoke for [null] due to overlapping prototypes between: [class java.io.Reader] [class java.lang.String]

http://image1.cytomine.be/image/crop.png?fif=%2Fdata%2Fbeta.cytomine.be%2F14%2F14%2F1350548387044%2FPGP_POUMON_PBS_3_21_-_2012-08-08_11.07.24.jp2&mimeType=image/jp2&topLeftX=10000&topLeftY=19440&width=1500&height=1500&imageWidth=34816&imageHeight=29440&mask=true%3Freviewed%3Dtrue&resolution=0.65

The error is triggered by the presence of ?mask=true
