### ISSUE TITLE
JOB Aurora

### ISSUE THREAD

**Issue by stevben** [cytomine/Cytomine-core-legacy#1064]
Ecrire un JOB Aurora qui détecte les images envoyées par ONCODNA (abstract_image + les 4 clés BIG). Envoyer les notifications au BIG, marquées les abstract_image en cas de succès par une propriété supplémentaire.

**Comment by geektortoise** [comment]
https://github.com/cytomine/Cytomine-core/blob/master/grails-app/services/be/cytomine/integration/AuroraService.groovy
