### ISSUE TITLE
Question: what library does cytomine use to handle jpeg 2000 images ?

### ISSUE THREAD

**Issue by boxerab** [cytomine/Cytomine-core-legacy#1072]
Cool project. How do you open and server j2k images ?

Thanks,
Aaron

**Comment by geektortoise** [comment]
Hello.

We are using the iipsrv lib [github](https://github.com/ruven/iipsrv) with kakadu.

**Comment by boxerab** [comment]
Thanks. I understand that iipsrv is going to be adding support for OpenJPEG. Do you have plans to support that codec as well as kakadu ?

**Comment by geektortoise** [comment]
We follow carefully the evolution of iipsrv to a full support of JP2 with OpenJPEG but we have performance constraints.
As I see [here](https://github.com/ruven/iipsrv/issues/14) OpenJPEG is currently 100x slower than Kakadu.

As you can see in our Cytomine-bootstrap repository, we have a Docker container specific to iipsrv with JP2 support. We will be happy to have only one iipsrv to deploy for TIFF & JP2000 files (and switch from Kakadu to OpenJPEG) when the performances of OpenJPEG will be comparable to Kakadu.

**Comment by boxerab** [comment]
Thanks. If the ratio was 3 times slower than Kakadu, would it be feasible to switch to another library.
Because, I happen to be working on a high performance fork of OpenJPEG : 
https://github.com/GrokImageCompression/grok
It uses the same interface as OpenJPEG, but performance for single image decode is around 3 times slower than latest Kakadu. I am hoping to improve this to half Kakadu speed.

**Comment by geektortoise** [comment]
Hello.
It sounds interesting. 
I think I will create a Dockerfile for iipsrv with OpenJPEG for people who want to test cytomine with OpenJPEG (or your fork) soon.
But, as iipsrv, the speedest lib will always be the default lib. ;-)

**Comment by boxerab** [comment]
Sounds good. I think you will want to support at least one open source codec.
