### ISSUE TITLE
Issue creating postgis docker on CentOS7

### ISSUE THREAD

**Issue by jacmarjorie** [cytomine/Cytomine-core-legacy#1073]
Creating docker images on CentOS Linux release 7.2.1511 (Core):

`sudo ./start_deploy.sh` complained:

```
postgis_data container is not running !
db container is not running !
```

docker logs show something along the lines of:

```
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
```

I was able to fix this by adding to postgis Dockerfile:

`ENV DEBIAN_FRONTEND noninteractive`

Just wanted to leave a note: if adding this line doesn't cause any issues on the suggested Ubuntu setup might be worth adding. 

Thanks!

**Comment by geektortoise** [comment]
Hello.

I have deployed on multiples CentOS7 without this problem. :/
I will test your modification.

Thanks.

**Comment by jacmarjorie** [comment]
Worth mentioning that I was also installing this on an older version of CentOS6, and was running into the same postgis issue. 

Thanks!

**Comment by mcwrinn** [comment]
Thanks; I was hitting the same issue on a CentOS7 installation here, and the ENV fix worked.
