### ISSUE TITLE
Users roles incorrectly labbeled in "Custom UI Configuration" in "Configuration" tab of a project

### ISSUE THREAD

**Issue by gvincke** [cytomine/Cytomine-core-legacy#1074]
In the Custom UI Configuration section of the Configuration tab inside a project, users role are "manager, user, guest" instead of "creator, managers, contributors".

**Comment by geektortoise** [comment]
The creator is not a role. 
A creator exists because one user have created the project and it's stored in the database but its rights are "manager", "contributor" or "guest" so a creator doesn't have more rights than other managers.

**Comment by geektortoise** [comment]
I'm on it.

**Comment by gvincke** [comment]
My conception was that there was only creators (typically a USER or ADMIN role), managers (ADMIN, USER or GUEST) and contributors (ADMIN, USERS or GUESTS) regarding to a project. OK creator is only a specific manager, but UI should be defined for project roles (managers, contributors) and not for platform roles (ADMIN, USER, GUEST). Mixing both levels is quite confusing.

**Comment by gvincke** [comment]
So if i well understand, the three columns are for managers (independently of their platform role), contributors of USER platform role, and contributors of GUEST platform role ? Is that right ?

**Comment by geektortoise** [comment]
You are right : 
http://doc.cytomine.be/display/DEVDOC/Customize+UI

"
ADMIN_PROJECT: a user admin in the project (<> global admin!),
USER_PROJECT: a user in the project with the role “ROLE_USER”,
GUEST_PROJECT: a user in the project with the role “ROLE_GUEST”
"

**Comment by gvincke** [comment]
Mhmmm. OK. Will think about trying to explain this quite clearly to final users... :-/
