### ISSUE TITLE
Add possibility to "hard delete" files unused or in error status in storage

### ISSUE THREAD

**Issue by gvincke** [cytomine/Cytomine-core-legacy#1080]
It should be VERY usefull to be able to hard-delete files in storage. For several reasons : 
- They are unused
- Their name is incorrect
- They are corrupted (mainly .zip archives with wrong inside structure)
- They are in an unsupported format
  etc.

**Comment by geektortoise** [comment]
With the new uploaded files architecture of v1.2 it is now possible.
