### ISSUE TITLE
Impossible to delete a user

### ISSUE THREAD

**Issue by gvincke** [cytomine/Cytomine-core-legacy#1084]
When connected as an ADMIN, in the admin panel, it is possible to add and edit users. Not to delete them. It could be very convinient to disable an account (not deleted but not allowed to connect anymore), and to delete some too. With or without their associated data (images, projects, annotations, descriptions, properties, ontologies, and so on).

**Comment by aled88** [comment]
Hello i have problem with this too. As an admin how to delete user and block new registration?

**Comment by VMFnet** [comment]
It seems this bug is still present : i cannot delete users when logged as admin.

**Comment by geektortoise** [comment]
You can now lock (and unlock) an user via the admin Panel in the UI.

Users cannot login as long as they are locked and if a user is currently connected, he will be forced logged out after few seconds.

It is not yet a true delete but it allows you to kick users on your instance.

**Comment by geektortoise** [comment]
See #1199 for evolution
