### ISSUE TITLE
In storage give more information on real files on disk

### ISSUE THREAD

**Issue by gvincke** [cytomine/Cytomine-core-legacy#1088]
Some formats are not used natively. If i upload a JPEG, it will be converted in flat TIFF by bioformat, and then this flat TIFF will be convert in pyramydal TIFF using vips. So for one JPEG file i have 2 TIFF files, and only the last one is used by the viewer using openslide.
So to clarify this for users, and understand why the disk storage seems more full than it should be it would be usefull to list all derived files in storage, wuth informations like format(flat tiff, pyr tiff, etc), process that have created it (uploaded file, file created by bioformat or vips or ...), and weight on disk.

**Comment by geektortoise** [comment]
Precision : JPEG files are only "vipsed".

**Comment by gvincke** [comment]
OK so JPEG -> vips -> pyramidal TIFF -> viewer (openslide ?)
BUT ;-)
if i upload a .zip contaning Olympus produced images : .zip -> .vsi + folder with .ets ->  bioformat -> enormous flat TIFF -> vips -> pyramidal TIFF -> viewer (openslide ?)
SO : for one file uploaded (zip) i have the original zip file, the .vsi and corresponding .ets in a folder, and 2 TIFF, one flat and one pyramidal. Lot of stuff that should be useful to know about ;-)

**Comment by geektortoise** [comment]
On the master branch.
