### ISSUE TITLE
Implement add_annotations request

### ISSUE THREAD

**Issue by waliens** [cytomine/Cytomine-core-legacy#1100]
Currently, it is not possible to add several annotations to an image with a single request. 
It would be great to be able to: 

1. submit a list of new annotations with a single request 
2. optionally associate terms and probabilities to the new annotations without having to issue another request (or another request per annotation)

**Comment by geektortoise** [comment]
Fixed with commit 9a08997b608bb362b846020c18c91c4f9e8271ae
