### ISSUE TITLE
Links between annotations

### ISSUE THREAD

**Issue by rmaree** [cytomine/Cytomine-core-legacy#1102]
Sometimes there are some sort of relations/links between annotations coming from multiple images, e.g. an annotation in image1 (modality1)  depicts the same object than an annotation in image2 (modality2). In the annotation panel, it would be nice to have a "Link" field (below the Description field) that allows to enter urls or annotation identifiers to link the current annotation to these other annotations. These links should be clickable so that we can then jump to these linked annotations.
We have to think about the data model: do we use a new table to encode links, or do we use the properties?

**Comment by geektortoise** [comment]
We implemented the tag feature that will allow you to associate a named tag to a Cytomine object.

It is a semantic linking between objects all across the platform.

The search has been modified to allow you to search all annotations (independent of the images)  with the tag X, all the images (independant of the project) with the tag Y.

So for the same semantic meaning, you will be able to retrieve all the annotations sharing this meaning.
