### ISSUE TITLE
Pink tiles in the image browser.

### ISSUE THREAD

**Issue by sparrisable** [cytomine/Cytomine-core-legacy#1110]
I looked at the "Known problems of 1.0" document, http://confluence.cytomine.be/display/PubOp/Known+problems+of+v1.0, but I think I have an issue that is not listed there.

My problem is that when I try to access my cytomine server externally then I get "ERR_NAME_NOT_RESOLVED" in my browser console. 

According to the browser console, the browser tries to access "atool-ims" to display the multi-resolution image but this gives "ERR_NAME_NOT_RESOLVED"
 
It works if I configure my desktop computer that runs the browser as follows:
"Primary DNS suffix of this computer"  = "cv.se"
(according to https://technet.microsoft.com/en-us/library/cc794784(v=ws.10).aspx)
Then "atool-ims" will be intepreted as "atool-ims.cv.se" and that works.

My configure.sh looks like this:
...
CORE_URL=atool.cv.se
IMS_URLS="[atool-ims.cv.se,atool-ims2.cv.se]"
...

"atool-ims.cv.se" is accessible in the browser but "atool-ims" is not accessible in the browser from my desktop (unless I set Primary DNS as described above).

So my problem is that the cytomine browser code uses "atool-ims/image..." instead of "atool-ims.cv.se/image...".

My IMS /etc/hosts, it looks like this:
root@2d6b0e078d25:/# cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.4      2d6b0e078d25
#Custom adding
172.17.0.1       atool.cv.se
172.17.0.1       atool-iip-base
172.17.0.1       atool-iip-cyto
172.17.0.1       atool-iip-jp2000
172.17.0.1       atool-ims
172.17.0.1       atool-ims2

I don't understand why it uses "atool-ims" instead of the full adress "atool-ims.cv.se" as is stated in configure.sh
(in my real setup "atool" and "cv.se" is actually renamed, but it is the same structure)

I would be grateful for any suggestions of what I may be doing wrong.

**Comment by geektortoise** [comment]
Well, it is strange. :/

I presume than you have tried to print the IMS urls value in the deploy.sh et start_deploy.sh script with a simple echo "$x" ?

Are the URLs already wrong at the run of start_deploy ?

**Comment by sparrisable** [comment]
I added the print out and ran restart_keep_data.sh and the output was:
[atool-ims.cv.se,atool-ims2.cv.se]

And when I logged in externally via a mobile phone hotspot then it worked. We will do some more tests just to make sure that there where no configuration errors in the test setup but it looks promising.

So basically a restart_keep_data.sh seems to have fixed my problem.

**Comment by sparrisable** [comment]
We have tested it is all good so far.
