### ISSUE TITLE
Upload not working, probably misconfiguration on my part.

### ISSUE THREAD

**Issue by sparrisable** [cytomine/Cytomine-core-legacy#1113]
I have a problem with uploading images on my Cytomine server. I get to the upload screen and I "Add Files..." but when I "Start upload" then I get "Error: true".

If I use my UPLOAD_URL from the config file directly in a web browser then I get the regular cytomine log in screen. I think this is wrong since I have an old cytomine server where uploading is working and on this server I get the "Welcome to nginx!" screen when I enter the UPLOAD_URL.

I have spent some time on trying to figure out why uploading fails and I was thinking that maybe you have some ideas on what could be wrong.
(I have double checked that the configuration.sh file for my old working cytomine server and for my new cytomine server is matching in relavant parts)

Thanks in advance for any ideas.

(I suspect that the error might be port related but port 80 is open externally and if read the documentation correct this should be enough)

**Comment by geektortoise** [comment]
Hello, 
Can you run the reporting script and send the result at  info@cytomine.be ?

**Comment by sparrisable** [comment]
Hello, 

I was able to solve my problem but thank you for your offer to help.

The problem was that I modified the configure.sh file and rebooted the server but Cytomine did not use my updated variables, it took some time before I realised this. In this step I believe that I had the URL variables wrong, the result was that when I "did Start upload" then I got "Error: true". (before any actual uploading started)

To make sure that Cytomine used the updated variables in configure.sh I ran "restart_keep_data.sh" and I believe that this made the upload of image data work. The progress bar displayed the upload but when the image data transfer was complete then I got "Error: true" instead.

In this case the log of the ims server indicated that my upload path was wrong:
"chmod: cannot access ‘/home/ubuntu/cytomine/data_path/data/28/1503672497174’: No such file or directory"

This was strange because the configure.sh did not contain the above path any more, it was an old value.

After doing a "hard restart",

```
sudo sh ./clean_docker.sh
sudo sh ./start_deploy.sh
```

then Cytomine used the updated path specified in the configure.sh.


If I reconfigure by modifying configure.sh is it required to run "./clean_docker.sh ./start_deploy.sh" to make sure that the new values are actually used?

Thank you for your great job with Cytomine.

**Comment by geektortoise** [comment]
Hello,
It is really strange. 
Usually, a restart_keep_data.sh will use the new values as you can see here : 
https://github.com/cytomine/Cytomine-bootstrap/blob/master/start_deploy.sh#L20

Maybe the configure file is not found when you run the restart_keep_data script. :/
Did you tried to run it from the Cytomine-bootstrap folder ?

Maybe these lines don't work on your OS.
https://github.com/cytomine/Cytomine-bootstrap/blob/master/restart_keep_data.sh#L18

What is your OS ?

**Comment by sparrisable** [comment]
Yes, I ran it from the Cytomine-boostrap folder.

The OS is Ubuntu 16.04.2 LTS

I tried to set the path and it looks correct:
```
ubuntu@ip-172-31-14-36:~/cytomine/Cytomine_src/Cytomine-bootstrap$ cat pr_test.sh
path=$( cd "$(dirname "${BASH_SOURCE}")" ; pwd -P )
echo path:
echo $path
ubuntu@ip-172-31-14-36:~/cytomine/Cytomine_src/Cytomine-bootstrap$ ./pr_test.sh
path:
/home/ubuntu/cytomine/Cytomine_src/Cytomine-bootstrap
```

I agree, it is strange.
