### ISSUE TITLE
Question: Can a binary mask be used as annotation?

### ISSUE THREAD

**Issue by ghost** [cytomine/Cytomine-core-legacy#1114]
Is there a way to add annotations to an image using a binary mask as reference?

For example, suppose I have generated a binary masks of epidermis regions in a set of images. Can I upload the masks to my Cytomine instance and apply the masks as image annotations for the epidermis term defined in my project ontology?

Thanks and all the best!

**Comment by rmaree** [comment]
Hello,
You can convert your binary masks into polygon coordinates at the client side.
See e.g. in Python here:
https://github.com/cytomine/Cytomine-python-datamining/blob/master/cytomine-applications/segmentation_prediction/image_prediction_wholeslide.py
See calls to utilities functions/classes Objectfinder, convert_to_real_coordinates, get_geometries.,... Then use add_annotation and add_annotation_term functions which make http requests using the API.
Ok?

**Comment by ghost** [comment]
Thank you for the tips! This will require that the masks already be uploaded to a project on cytomine, so that functions/classes like WholeSlide and ImageInstance will be workable, is that correct? I am hoping to keep the masks local and just upload annotations. Is there a way to generate an image_instance locally?

**Comment by rmaree** [comment]
No, these Python functions to upload contour coordinates are working on local masks, you don't need to upload the masks.
You can download image instances (in native format) or tiles (in PNG/JPG using the reader working on the WholeSlide object, communicating through the Rest API to get tiles) or image thumbnails using the Python client. Then you process images/tiles locally, generate masks, then you detect the contours (using e.g. opencv findcontours) in these local masks and then upload their whole slide coordinates only (specifying the imageinstance id).

**Comment by waliens** [comment]
For the record, in the context of another project, we have been developing a small library for converting mask images to other formats (e.g. polygons): https://github.com/Neubias-WG5/AnnotationExporter
This implementation covers more corner-cases then ObjectFinder,... and should be more efficient.
