### ISSUE TITLE
How to migrate Cytomine to new hardware?

### ISSUE THREAD

**Issue by sparrisable** [cytomine/Cytomine-core-legacy#1115]
I need to move data from an existing Cytomine server and I did not find explicit documentation regarding this. I basically see three ways to do this:

1) Download annotations,users etc manually from the existing database and upload them manually to the new Cytomine server. 

2) Export/replicate database contents of postgresql & mongodb and import them on the new Cytomine server.

3) Copy and move docker containers

Is there a recommended way to do this?
Has anyone experience of doing this?

**Comment by geektortoise** [comment]
Hello, 

the best way is to migrate only the data.

You will find documentation here : http://doc.cytomine.be/pages/viewpage.action?pageId=12910835

If you have some data relative to the jobs, you can save and migrate the content of the ALGO_PATH.

**Comment by sparrisable** [comment]
Great, thanks!
