### ISSUE TITLE
How to permanently delete an image from Cytomine, to free diskspace?

### ISSUE THREAD

**Issue by sparrisable** [cytomine/Cytomine-core-legacy#1116]
I have problem with deleting images using the Cytomine user interface.

I am logged in as the admin user.
In the Storage list I get the list of images with the Action column displaying a blue "Delete" label. This label is not clickable though, the status of the two images that I want to delete are "UPLOADED", these images are between 45 and 65 GB in size. 

The other images listed have the Status "DEPLOYED" and these also have the blue Action label "Delete", same thing with these images - nothing happens if I click on the blue "Delete" label.

The manual describes how to remove an image from a project, but I want to delete the image permanently from the Cytomine server/disk. Is this possible using the user interface?

(I suspect that is not recommended to delete the image manually from the filesystem, since projects and annotations might exist that refers to the deleted image)

Updated: 2017-09-18: 14:31 
There are some images that are deletable, the delete button is usable for these images. It seems like these images are NOT part of any project.
My problem remain though, the two images that I want to delete  have the status "UPLOADED" and don't seem to be part of any project.

**Comment by geektortoise** [comment]
Hello, 
it is not yet possible to delete an image through the UI.

You need to do some SQL requests to get the uploaded_file you want to delete and cross informations with the storage_basepath to get the absolute file path of the image you want to delete.

**Comment by geektortoise** [comment]
With the new uploaded files architecture of v1.2 it is now possible.
