### ISSUE TITLE
uploading issue

### ISSUE THREAD

**Issue by chanyo** [cytomine/Cytomine-core-legacy#1117]
Hello,

Recently, we had an issue: our machine that hosts cytominedev was rebooted. 
In order to bring the suite of cytomine docker contains back online, we had removel all the current containers in the  process. 

After this issue, we were able to use cytomine again and upload some images. However, we had an issue that we cannot upload images using Cytomine UI.
When we upload image, it shows "Error true" message and I cannot find any images.

The only error I can see with a timestamp that corresponds to my upload is this one:
2017-10-20 22:28:49,975 [http-bio-8080-exec-1] ERROR storage.StorageController  - java.lang.NullPointerException: Cannot invoke method getBytes() on null object (… and a lot of java code entry points that follow …)
 
The first code entry point is at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:88)
 The error is associated with the cytomine/ims container.

Could you please let me know how to fix this issue?

Thanks

**Comment by geektortoise** [comment]
Hello, 

It is difficult to help you without more information.
Can you copy paste the stacktrace ?
