### ISSUE TITLE
Retrieve the last opened images in a given project

### ISSUE THREAD

**Issue by elodieburtin** [cytomine/Cytomine-core-legacy#1126]
/api/imageinstance/method/lastopened.json allowed to retrieve the last images opened by the current user.
It would be nice to have the possibility to specify a project, and retrieve last images opened in this particular project.

**Comment by geektortoise** [comment]
API entrypoint
/api/project/$project/user/$user/imageconsultation.json 
added

**Comment by elodieburtin** [comment]
Would it be possible to have a behaviour more similar to `/api/imageinstance/method/lastopened.json`? The new entrypoint returns image consultations, which means the same image can be returned several times, and it cannot be predicted how many entries should be fetched in order to display a given number of (distinct) images. This is different from `/api/imageinstance/method/lastopened.json` which always return unique images, even if those were opened multiple times. Having a consistency in the format of the response data would also be great!

**Comment by geektortoise** [comment]
In REST terms, 
 /api/project/$project/user/$user/imageconsultation.json
tell us than we will return the imageconsultation objects no matter if these distinct objects are related to the same image.

I will add a query parameter to fill your need.

**Comment by geektortoise** [comment]
https://github.com/cytomine/Cytomine-core/commit/6188d63e8b750234b3f3c7bc03c2956939089890

"distinctImages" as a query parameter added.
So add the ?distinctImages=true at the end of the url.
