### ISSUE TITLE
Provide the date of last activity in projects/images list

### ISSUE THREAD

**Issue by elodieburtin** [cytomine/Cytomine-core-legacy#1128]
When requesting the list of projects using GET /api/project.json, it would be useful to include in the response the date of the last activity performed in each project.

Similarly, the date of the last activity on each image could be returned when requesting the list of images.

**Comment by geektortoise** [comment]
Done with f645da2fcd99f6735e47f5d8813e1c859cba8030 and 60f0b765e61a62df045a24d39a2d24ddeabfd1e7

"withMembersCount" and "withLastActivity" parameters

**Comment by elodieburtin** [comment]
When using one of those parameters, the values of `ontology`, `ontologyName`, `numberOfReviewedAnnotations`, `retrievalDisable`, `retrievalAllOntology`, `isClosed`, `hideUsersLayers` and `hideAdminLayers` are set to null in response (for all projects).

**Comment by geektortoise** [comment]
This commit should fix it 
https://github.com/cytomine/Cytomine-core/commit/b5a06d758c7e2e4e7ff0e70036dd011731f7591e
