### ISSUE TITLE
Annotations clusters disappear when hiding the annotations without terms

### ISSUE THREAD

**Issue by elodieburtin** [cytomine/Cytomine-core-legacy#1130]
To reproduce the issue:
- Access an image containing so many annotations that they get clustered (e.g. https://demo.cytomine.coop/#tabs-image-1197641-1199600-0). Some of these annotations must have terms associated to them.
Result: clusters of annotations are displayed 
- In the right panel, under Ontology, uncheck the checkbox "Show annotations without terms"
Result: all clusters disappear, even those that contained annotations with terms

When zooming in the image, the annotations with terms are correctly displayed.

**Comment by geektortoise** [comment]
Fixed
