### ISSUE TITLE
Incorrect annotation count in viewer

### ISSUE THREAD

**Issue by elodieburtin** [cytomine/Cytomine-core-legacy#1131]
In right panel of viewer, under "Ontology", the terms applicable to the project are listed, along with the number of annotations associated to each term. However, this number is incorrectly computed, and always results in 0. We should either remove the (0) next to each term or fix the computation.

**Comment by geektortoise** [comment]
Currently, these counters are linked with the selected annotation and display the number of associated term on the selected annotation.
