### ISSUE TITLE
Cannot filter annotations in project with too many users and/or images

### ISSUE THREAD

**Issue by elodieburtin** [cytomine/Cytomine-core-legacy#1132]
When a project contains many images, the URL for fetching annotations in this project for a large subset of images can become very long as it contains the list of selected images identifiers. As a result, the server responses with an error 414 Request-URI Too Large.

In the application, it prevents the user from viewing the annotations (in annotations panel) when he/she selects too many images in the left panel: in such a case, no annotation at all is displayed (but the application does not display any error message).

Note that if all images are selected, this problem does not apply: indeed, in this case, the query parameter "images" is not included in the URL.

**Comment by geektortoise** [comment]
The 414 http error code is sent by the nginx proxy.

To allow huge URL, you need to
- add the line 
`large_client_header_buffers 4 16k;`
into your nginx configuration (and all the other proxies on the way)
- add the parameter
`maxHttpHeaderSize="16384"`
into the Connector tag of the tomcat (see here : https://serverfault.com/questions/56691/whats-the-maximum-url-length-in-tomcat ) (/etc/tomcat7/server.xml in the core container)
- restart your cytomine

Please, be aware that there exist limitations into the browser too.

**Comment by geektortoise** [comment]
Hello, 

You will find here ( 9d72fd7e9114944f325c09b626d0b8487e41f413 ) a new entrypoint allowing a POST request to make a search with a lot of parameters (to avoid the 414 error code, the parameters must be in the post body ).

As said previously, i can't fix the 414 error code so you must change your request to this new entrypoint to avoid it
