### ISSUE TITLE
When creating an annotation, incorrect term property in response

### ISSUE THREAD

**Issue by elodieburtin** [cytomine/Cytomine-core-legacy#1143]
When creating an annotation with `POST /api/annotation.json`, the response contains the newly created annotation. However, the property `term` always contains an empty array, even if terms were specified in the creation request. 

Remark: If subsequently fetching the created annotation with `GET /api/annotation/{id}.json`, the response correctly includes the associated terms.

**Comment by geektortoise** [comment]
Fixed by https://github.com/cytomine/Cytomine-core/commit/b5516cd2e406c242c9e22afd6b494c2ef3ba55d3
