### ISSUE TITLE
Incomplete data returned for userlayers

### ISSUE THREAD

**Issue by elodieburtin** [cytomine/Cytomine-core-legacy#1146]
When fetching the users layers for a particular image using `api/project/{idProject}/userlayer.json?image={idImage}`, the returned data does not always contain all fields for all layers. More specifically, some user (from my tests, it seems to always be a single one in the collection) only contains the following fields: class, id, created, updated, deleted, username and algo (missing fields: firstname, lastname, email...)

Example on demo.coop: https://demo.cytomine.coop/api/project/1012227/userlayer.json?image=1049959 (mobb user truncated)

**Comment by urubens** [comment]
Fixed in Cytomine-ULiege/Cytomine-core@08de56246c1a5419fff883d608002c36667e8e6a

**Comment by geektortoise** [comment]
Modifications of @urubens integrated.
