### ISSUE TITLE
Retrieve annotations from jobs and users

### ISSUE THREAD

**Issue by elodieburtin** [cytomine/Cytomine-core-legacy#1149]
When fetching annotations with `GET /api/annotations.json`, the `includeAlgo` parameter allows to specify that the response should include job annotations in addition to user annotations. However, when setting this parameter to true, the user annotations are not included in response.

Trying to fetch annotations from several jobs and several users by specifying the users and userjobs IDs in the `users` field does not work either: the response only includes one type of annotation.

Is there a way to fetch both types of annotations in one request, or should we always perform two requests in such situation? If the `includeAlgo` parameter aims at retrieving only the algo annotations, maybe it should be renamed (and/or documented) to clarify its use?

**Comment by geektortoise** [comment]
Hello, 

What are your parameters ?

In this block https://github.com/cytomine/Cytomine-core/blob/master/grails-app/controllers/be/cytomine/api/ontology/RestAnnotationDomainController.groovy#L216 , we have an union of algoAnnotations and userAnnotations.

**Comment by elodieburtin** [comment]
Denoting `idUser` the identifier of a human user, `idUserJob` the identifier of a user job and `idImage` the identifier of an image instance where both the human user and the user job created annotations, here are the results I obtain:
1. `GET /api/annotation.json?images={idImage}&users={idUser}` returns `x` results
2. `GET /api/annotation.json?images={idImage}&users={idUserJob}` returns `y` results
3. `GET /api/annotation.json?images={idImage}&users={idUser},{idUserJob}` returns `x` results (same as 1.)
4. `GET /api/annotation.json?images={idImage}&users={idUser},{idUserJob}&includeAlgo=true` returns `y` results (same as 2.)
5. `GET /api/annotation.json?images={idImage}&users={idUserJob},{idUser}` returns `y` results (same as 2.)

From the code, it seems that the user annotations that are joined to the algo annotations are not those created by the human users provided in `users` parameters. Rather, it is the user annotations for which a term was added by one of the user jobs in the `users` parameters. Therefore, the human users identifiers do not seem to be taken into account.

**Comment by geektortoise** [comment]
I created a new test class into a6ac1c158b80960b0124994c45c4241b65503f31

We can see that the search functionality for the annotations is not consistent and need to be rewritten.

I move this ticket to the next release.
