### ISSUE TITLE
Improve annotations draw on crop

### ISSUE THREAD

**Issue by elodieburtin** [cytomine/Cytomine-core-legacy#1151]
The image returned for `GET /api/annotation/{id}/crop.png?draw=true` could be improved in the following ways:
- Expand the returned area so that the contour of the annotation is fully visible (currently, it is sometimes cut by the border of the image) and so that the context is visible (ideally, the padding should be proportional to the annotation size);
- Have a more precise drawing of the contour (currently, it seems to be simplified compared to what is displayed in the viewer).

**Comment by geektortoise** [comment]
For the second point, yes the annotation is simplified.
To avoid this behaviour, add the "complete" boolean parameter

**Comment by urubens** [comment]
For the first point, there is the "increaseArea" parameter which increases the crop area by multiplying original crop size by this factor.

FYI, at ULiege, we started to refactor the interaction between core and IMS to decrease the amount of code duplicates and avoid mixed and undocumented behaviors.

**Comment by elodieburtin** [comment]
Thanks ! By any chance, is there also a parameter for controlling the line thickness ?

**Comment by geektortoise** [comment]
No.
The thickness is currently the maxSize / 60

See https://github.com/cytomine/Cytomine-IMS/blob/master/grails-app/services/cytomine/web/ImageProcessingService.groovy#L350

Would it be useful for you ?

**Comment by geektortoise** [comment]
I added the parameters
thickness (integer), square (boolean) and color (string (hexa code)) in Core and IMS
