### ISSUE TITLE
Tag system

### ISSUE THREAD

**Issue by elodieburtin** [cytomine/Cytomine-core-legacy#1153]
Some users have requested the possibility to have a tag system, allowing them to easily associate tags (keywords) to projects and/or images. It should then be possible to efficiently filter projects/images according to the tags they were associated with.

Do you think it could be handled with properties? Are there methods allowing to efficiently fetch objects having properties with a given key and a value belonging to a provided list? Or is is better to introduce a new concept?

**Comment by geektortoise** [comment]
As the property system exists, it is not a prior features for the Open Source for now.

**Comment by geektortoise** [comment]
The Tag concept has been implemented.

You can create tag and associate them to projects, images, annotations and jobs.

You can also search objects with a filter on these associated tags.
