### ISSUE TITLE
Round global size in Storage

### ISSUE THREAD

**Issue by gvincke** [cytomine/Cytomine-core-legacy#1158]
On Storage, the size of a file is rounded to 2 digits. The Global size (uploaded file + temporary and final files when a conversion is needed) is not. Please round this global value too. The non rounded value can be accessed if necessary une "Details" modal box.
Thanks.

**Comment by geektortoise** [comment]
Already fixed with
https://github.com/cytomine/Cytomine-core/commit/70c473eed1d0488711684e8cf7786a01d21caa5b

I will make a release soon (end of January) with this fix.
