### ISSUE TITLE
Do not return image names in JSON if project is in blind mode

### ISSUE THREAD

**Issue by elodieburtin** [cytomine/Cytomine-core-legacy#1160]
Currently, when a project is in blind mode, the images names are not displayed in the UI. However, they are visible in the JSON. Ideally, this should not be the case: the user should not be able to retrieve the image name by any way.

Moreover, it would be better to use a randomly generated string/number as name of the image, instead of a Cytomine ID. Ideally this randomly generated sequence should be updated each time the blind mode is disabled then re-enabled.

**Comment by geektortoise** [comment]
Done by 8699c8f6737aac45838340213babbb0f43033b42
