### ISSUE TITLE
issue with "#" character in filename

### ISSUE THREAD

**Issue by delimz** [cytomine/Cytomine-core-legacy#1161]
An image containinng # in the filename  cannot be downloaded or displayed properly,

https://demo.cytomine.coop/#tabs-images-1012227
the image 2313567 with filename F3-744-8AF-2 (#2 en bas choisi).svs

generated download url : 
https://demo-ims2.cytomine.coop/image/download?fif=/data/images/678328//1547135829409/F3-744-8AF-2__#2_en_bas_choisi_.svs&mimeType=openslide/svs

when replacing "#" in the resulting url by "%23" the image becomes downloadable.

**Comment by geektortoise** [comment]
Hello, 
It was complicated to encode the filename in utf-8 when reaching IMS, then decode it, decompose the URL and reencode the good part when reaching iip.

So, I avoid these chars when uploading.
 https://github.com/cytomine/Cytomine-IMS/commit/4a968d571956da437a284c0353d5ff8760236646

Your file is now fixed (I made a DB update)
