### ISSUE TITLE
How to select annotation behind another annotation

### ISSUE THREAD

**Issue by anttikos** [cytomine/Cytomine-core-legacy#1179]
I have drawn an annotation that covers the whole tissue with freehand polygon tool, and a smaller one annotation a specific feature, which boundaries are inside the bigger annotation's boundaries. Is there a way to select the smaller one that is behind the big one, or is it possible to send the bigger one  backward, and/or bring the smaller one to front (change their z-index?)

**Comment by rmaree** [comment]
Dear anttikos,
I guess your two annotations (the big one and the small ones) have different terms from the ontology that you defined (e.g. "tissue section" for the big one, and "specific" for the small one). In that case, it is possible to make the "tissue section" annotation invisible by going to the ontology panel (right panel in the V2 front-end) and unselecting the checkbox under the <span class="far fa-eye"></span> symbol (eye) so that you can now select the small one. OK ?

**Comment by anttikos** [comment]
Thank you for you answer rmaree, and thanks for the tip of using different terms for different annotations, that makes lots of sense, and I should do that no matter what. But, I was also thinking of use case where I would like to see both of the annotations at the same time, and to be able to quickly switch between the two. Or, in case I would have 10 overlapping annotations, I would need to enable/disable layers often (although I don't haven't seen need for this, yet). 

In case this is useful: Here is a quick trick I did in order to enable the annotation selection within the same annotation layer, even if they are located behind others .. the idea being to draw them in order from bigger to smaller. It's probably not perfect solution by all means, and maybe it's not a proper place for this kind of sorting, but this seemed to work pretty well when quickly tested.

AnnotationLayer.vue:
`arrayAnnots = await this.fetchAnnots(extent);`
`        // Order by size, so bigger ones are always sent to back`
`        arrayAnnots.sort( `
`          function( a, b ) {`
`            if( a.area < b.area ) return 1;`
`            else return -1;`
`          }`
`        );`

**Comment by geektortoise** [comment]
Hello, 

Thanks @rmaree for your response and solution.
Thanks @anttikos for your ticket and the solution.
As this solution will not cover all cases, I made another ticket here 
https://github.com/cytomine/Cytomine-Web-UI/issues/13
and I close this one

Have a nice day !

**Comment by geektortoise** [comment]
Hi @anttikos , 

Your contribution has been integrated in the Web-UI code and released in its 1.1.1 release. :-) 

Have a nice day.

For more details : https://github.com/cytomine/Cytomine-Web-UI/issues/13

**Comment by anttikos** [comment]
I'm glad to hear you got it solved, and I'm happy that I was able to be part of the solution :)
