### ISSUE TITLE
Cannot re-add a deleted annotation-term link

### ISSUE THREAD

**Issue by urubens** [cytomine/Cytomine-core-legacy#1191]
With the introduction of soft deletion for annotations and related ( e92d223e30741811615ad9a361a4d7ba574a240f ), the deleted objects are poorly handled. In the case of annotation-term links, at least,
* a deleted annotation-term link cannot be re-added
* deleted annotation-term links are returned in single annotation GET request.

**Comment by geektortoise** [comment]
Hello, 

Thanks for the PR.

Have a nice day !
