### ISSUE TITLE
Custom URL configuration does not work

### ISSUE THREAD

**Issue by mizjaggy18** [cytomine/Cytomine-core-legacy#1201]
Hi @geektortoise and Cytomine developers,

We have set up Cytomine and it was working perfectly locally. Then we decided to host it using our university's domain. The configuration.sh is as below:

> CORE_URL=cytomine.university.edu.my
IMS_URL1=cytomine.university.edu.my/ims1
IMS_URL2=cytomine.university.edu.my/ims2
UPLOAD_URL=cytomine.university.edu.my/upload

The /etc/hosts remains the same:

> 127.0.0.1     localhost-core
127.0.0.1     localhost-ims
127.0.0.1     localhost-ims2
127.0.0.1     localhost-upload
127.0.0.1     rabbitmq

But again I am having problem uploading and viewing images (like [this issue](https://github.com/cytomine/Cytomine-bootstrap/issues/34) last time). I have reinitialized and restarted Cytomine several times but it does not work. Hope it can be solved without reinstalling Cytomine all over again. Please advise and thank you.

**Comment by geektortoise** [comment]
Hello, 

Thanks for pointing that out, I improved the documentation.
In the current bootstrap version, it must be 4 different URLs.
In your case, cytomine.university.edu.my/ims1 is a specific path of cytomine.university.edu.my URL.

Trying with
CORE_URL=cytomine.university.edu.my
IMS_URL1=cytomine-ims1.university.edu.my
IMS_URL2=cytomine-ims2.university.edu.my
UPLOAD_URL=cytomine-upload.university.edu.my

Should do the work. :-)

**Comment by mizjaggy18** [comment]
Alright, all perfect now with the suggested solution. Thanks @geektortoise :)

**Comment by geektortoise** [comment]
You're welcome.

We plan to improve this situation for the end of the year.
