### ISSUE TITLE
Failed to delete the uploaded file(unexpected error)

### ISSUE THREAD

**Issue by vewe-richard** [cytomine/Cytomine-core-legacy#1225]
Can not delete image
Description :
1. upload image
2. add image to a project
3. delete image from project
4. delete image for #storage page, it reports "Failed to delete the uploaded file(unexpected error)"

sudo docker logs -f core
29-10-2022 00:59:22,631 WARN ConstraintException - This slice be.cytomine.image.AbstractSlice : 2418 cannot be deleted as it has already been insert in projects [test2]
29-10-2022 00:59:22,631 ERROR RestController - This slice be.cytomine.image.AbstractSlice : 2418 cannot be deleted as it has already been insert in projects [test2]

But I had deleted this image from test2 project.

docker image version
cytomine/core:v3.2.3

**Comment by vewe-richard** [comment]
![image](https://user-images.githubusercontent.com/13496173/198759659-a652134e-dccd-423e-aa1a-c982339a1aa0.png)

**Comment by vewe-richard** [comment]
Fixed

**Comment by aayio** [comment]
@vewe-richard I'm sorry if I missed it, but how did you fix this? Thank you.
