### ISSUE TITLE
[CYTO-1071] Overview explore

### ISSUE THREAD

**Issue by stevben** [cytomine/Cytomine-core-legacy#53]
<b><i>[reporter="rmaree", created="dim., 24 nov. 2013 09:24:13 +0100"]</i></b>

<p>L'overview en mode explore/review est souvent buggée: on ne voit pas toute l'image.</p>

**Comment by stevben** [comment]
<b><i>[author="lrollus", created="ven., 29 nov. 2013 10:42:03 +0100"]</i></b>

<p>Dépend de l'image?</p>

**Comment by loic911** [comment]
cannot reproduce
