### ISSUE TITLE
[CYTO-314] Parcours des annotations de la lame courante

### ISSUE THREAD

**Issue by stevben** [cytomine/Cytomine-core-legacy#799]
<b><i>[reporter="stevben", created="mer., 13 juil. 2011 16:26:09 +0200"]</i></b>

<p>Un truc bien pratique, ce serait un bouton "next", toujours placé au même endroit (p.ex. à côté de la croix) qui permettrait de passer à l'annotation suivante dans la liste sans effort.</p>

**Comment by geektortoise** [comment]
Linked to old front-end
